### ISSUE TITLE
Doesn't work with newer kernel versions

### ISSUE THREAD

**Issue by kbader94** [lin-bus/linux-lin#3]
In addition to your previously mentioned kernel changes & changing the LDISC, the project doesn't work on newer kernel versions because of changes in alloc_netdev. Changing sll_alloc() to:

		size = ALIGN(sizeof(*sl), NETDEV_ALIGN) + sizeof(struct can_ml_priv);
		dev = alloc_netdev(size, name, NET_NAME_UNKNOWN, sll_setup);
`
and

	sl = netdev_priv(dev);
	dev->ml_priv = (void *)sl + ALIGN(sizeof(*sl), NETDEV_ALIGN);

seems to make it run on kernel v5.10.17

**Comment by kbader94** [comment]
Yea the code is kind of pseudo code, you'd definitely want an if statement to handle different versions I just didn't get to finding which version it changes in yet. I didn't realize any of these repos were active I'm definitely willing to fork yours and work towards getting this working with newer kernel versions. It's kind of on my back burner right now, though I do plan on getting it fully implemented at least with my device(a Raspberry pi 4) but from what I understand universal support is out the door without kernel support for universal 1 byte fifo buffers.

**Comment by ppisa** [comment]
I have prepared pull request based on your patches, redundant patches squashed, line discipline number changes separated.

As for the module parameters, control of master/slave by module parameters is problematic, because you can have more interfaces. So my preference is to use two line disciplines or find way how to send parameter during attach. To document which number is used for master and slave, I suggest t export numbers through sys or proc  interface. One option is to add module paramenetrs ldisc_master and ldisc_slave which allows to obtain actual values used by module registration from

  /sys/module/sllin/parameters

for now before we get registered into mainline kernel.

Please test with available kernels that I have not introduced some problem.

**Comment by ppisa** [comment]
@kbader94 work and testing resolved compatibility with 5.10+ linux kernels. Thanks.

It is highly probable that compatibility would be broken again as mainline evolves, please open new issue in such case. Long term solution is to mainline slLIN.
